# application.yml
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
# application.yml
aliyun:
  sls:
    endpoint: cn-hangzhou.log.aliyuncs.com
    project: my-app-logs
    logstore: app-log-store
    accessKey: ${ENV_SLS_KEY}
    accessSecret: ${ENV_SLS_SECRET}
rocketmq:
  name-server: 127.0.0.1:9876  # NameServer地址
  producer:
    group: your-producer-group # 生产者组名
    send-message-timeout: 3000 # 发送超时(ms)
    retry-times-when-send-failed: 2 # 同步发送失败重试次数